export enum Translate {
  lastName = "Фамилия",
  firstName = "Имя",
  secondName = "Отчество",
  gender = "Пол",
  role = "Роль",
  phoneNumber = "Номер телефона",
  dateOfBirth = "Дата рождения",
  country = "Страна",
  city = "Город",
  area = "Область",
  street = "Улица",
  houseNum = "Номер дома",
  flat = "Квартира",
  series = "Серия",
  pasportNum = "Номер",
  issuedBy = "Кем выдан",
  placeOfRegistration = "Место регистрации",
  dateOfIssue = "Дата выдачи",
}
